Document: psb-kmd
Title: Debian psb-kmd Manual
Author: <insert document author here>
Abstract: This manual describes what psb-kmd is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/psb-kmd/psb-kmd.sgml.gz

Format: postscript
Files: /usr/share/doc/psb-kmd/psb-kmd.ps.gz

Format: text
Files: /usr/share/doc/psb-kmd/psb-kmd.text.gz

Format: HTML
Index: /usr/share/doc/psb-kmd/html/index.html
Files: /usr/share/doc/psb-kmd/html/*.html

  
