pref("grabAndDrag-version", "0.0.0");
pref("grabAndDrag.on", true);
pref("grabAndDrag.grabCursor", "url(chrome://grabanddrag/skin/grab.png) 10 4, move");
pref("grabAndDrag.grabbingCursor", "url(chrome://grabanddrag/skin/grabbing.png) 10 4, move");
pref("grabAndDrag.togKey", 68);
pref("grabAndDrag.useCtrl", false);
pref("grabAndDrag.useAlt", true);
pref("grabAndDrag.useShift", true);
pref("grabAndDrag.dragInc", "1");
pref("grabAndDrag.mult", "1");
pref("grabAndDrag.sbmode", false);
pref("grabAndDrag.samecur", true);
pref("grabAndDrag.reverse", false);
pref("grabAndDrag.flickon", true);
pref("grabAndDrag.flickspeed_ppms", "2");
pref("grabAndDrag.flicktimelimit", "150");
pref("grabAndDrag.flickwhole", 0);
pref("grabAndDrag.momOn", true);
pref("grabAndDrag.momExtent", "500");
pref("grabAndDrag.momVariation", "0.5");
pref("grabAndDrag.momFriction", "0");
pref("grabAndDrag.smoothStop", true);
pref("grabAndDrag.button", 0);
pref("grabAndDrag.qtOnCnt", 2);
pref("grabAndDrag.qtOffCnt", 1);
pref("grabAndDrag.qtOffCopy", false);
pref("grabAndDrag.preLevel", 2);
pref("grabAndDrag.strict", false);

pref("extensions.{477c4c36-24eb-11da-94d4-00e08161165f}.description", "chrome://grabanddrag/locale/grabanddrag.properties");
