#! /bin/sh

set -e

rm -f /etc/X11/Xsession.d/25samsung-q1-ultra-config_startup

if [ -x "/etc/init.d/samsung-q1-ultra-keycode-setup" ]; then
        update-rc.d samsung-q1-ultra-keycode-setup defaults >/dev/null
        if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
                invoke-rc.d samsung-q1-ultra-keycode-setup start
        else
                /etc/init.d/samsung-q1-ultra-keycode-setup start
        fi
fi
[ -x "/etc/acpi/powerbtn.sh" ] && mv /etc/acpi/powerbtn.sh /etc/acpi/powerbtn.sh.acpid
[ -x "/etc/acpi/powerbtn.sh.ume" ] && cp /etc/acpi/powerbtn.sh.ume /etc/acpi/powerbtn.sh

#DEBHELPER#
