#!/bin/bash
#
# Create the symbol file  that is used by grub-fast-resume
#   Copyright 2007 Xu Martin <martin.xu@intel.com>
#
# This file is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
#
# Contributors:
#	Frank Li <frank.li@intel.com>

if [ !  -f $1 ] 
then
    echo Error: File $1 does not exist
    echo Usage: $0 symble_file out_put_file
    exit 1
fi

if [ -z $2 ]
then
    echo need the out-put-file
    echo Usage: $0 symble_file out_put_file 
    exit 1
fi

symble_file=$1
out_put_file=$2

uname -r > $out_put_file

uname -v >> $out_put_file

grep -w saved_context_ebx $symble_file >> $out_put_file
if [ $? != 0  ]
then
    echo Can not find "saved_context_ebx" 
    exit 1
fi

grep -w saved_context_esp $symble_file >> $out_put_file
if [ $? != 0  ]
then
    echo Can not find "saved_context_esp" 
    exit 1
fi

grep -w saved_context_ebp $symble_file >> $out_put_file
if [ $? != 0  ]
then
    echo Can not find "saved_context_ebp" 
    exit 1
fi

grep -w saved_context_esi $symble_file >> $out_put_file
if [ $? != 0  ]
then
    echo Can not find "saved_context_esi" 
    exit 1
fi

grep -w saved_context_edi $symble_file >> $out_put_file
if [ $? != 0  ]
then
    echo Can not find "saved_context_edi" 
    exit 1
fi

grep -w saved_context $symble_file >> $out_put_file
if [ $? != 0  ]
then
    echo Can not find "saved_context" 
    exit 1
fi

grep -w saved_context_eflags $symble_file >> $out_put_file
if [ $? != 0  ]
then
    echo Can not find "saved_context_eflags" 
    exit 1
fi

grep -w __nosave_begin $symble_file >> $out_put_file
if [ $? != 0  ]
then
    echo Can not find "saved_context_eflags" 
    exit 1
fi

grep -w __nosave_end  $symble_file >> $out_put_file
if [ $? != 0  ]
then
    echo Can not find "saved_context_eflags" 
    exit 1
fi
