#!/usr/bin/env python
# vim: ai ts=4 sts=4 et sw=4

#    Copyright (c) 2007 Intel Corporation
#
#    This program is free software; you can redistribute it and/or modify it
#    under the terms of the GNU General Public License as published by the Free
#    Software Foundation; version 2 of the License
#
#    This program is distributed in the hope that it will be useful, but
#    WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
#    or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
#    for more details.
#
#    You should have received a copy of the GNU General Public License along
#    with this program; if not, write to the Free Software Foundation, Inc., 59
#    Temple Place - Suite 330, Boston, MA 02111-1307, USA.

import sys, string, getopt
import dbus, dbus.glib, gobject

class App:
    def __init__(self):
        bus = dbus.SessionBus()
        self.service = bus.get_object('org.moblin.media',
                                      '/org/moblin/media')
        
    def play(self, url, mimetype, repeat):
        print self.service.dbus_service_play(url, mimetype, repeat)

    def connect(self, name):
        self.service.dbus_service_connect(name)

    def top_application(self):
        self.service.top_application()

if __name__ == '__main__':
    app = App()
    opts, args = getopt.getopt(sys.argv[1:], "h", ["help"])
    if(len(args)>=1):
        app.connect("Mozplugger")
        app.play(args[0], "foo", 1)
	app.top_application()

