#! /bin/sh

set -e

rm -f /etc/X11/Xsession.d/25crown-beach-config_startup

[ -x "/etc/acpi/powerbtn.sh" ] && mv /etc/acpi/powerbtn.sh /etc/acpi/powerbtn.sh.acpid
[ -x "/etc/acpi/powerbtn.sh.ume" ] && cp /etc/acpi/powerbtn.sh.ume /etc/acpi/powerbtn.sh

/usr/sbin/update-rc.d iusbc defaults
GCONF_CONFIG_SOURCE=xml::/etc/gconf/gconf.xml.defaults \
gconftool-2 --makefile-install-rule /etc/gconf/gconf.xml.defaults/iusbc.schemas

#normal boot optimization
/usr/sbin/update-rc.d -f keyboard-setup remove
/usr/sbin/update-rc.d -f console-setup remove
/usr/sbin/update-rc.d -f pcmciautils remove
#add the post service starting support
[ -L "/etc/rc2.d/S99post-service" ] && /bin/rm -f /etc/rc2.d/S99post-service
[ -x "/etc/init.d/post-service" ] && /usr/sbin/update-rc.d post-service start 99 2 .
[ -d "/etc/rcP.d" ] && /bin/rm -rf /etc/rcP.d
/bin/mkdir /etc/rcP.d
[ -L "/etc/rc3.d/S20iusbc" ] && /bin/cp -s  /etc/rc3.d/S20iusbc /etc/rcP.d
[ -L "/etc/rc2.d/S20iusbc" ] && /bin/rm /etc/rc2.d/S20iusbc -f

[ -L "/etc/rc3.d/S25bluetooth" ] && /bin/cp -s /etc/rc3.d/S25bluetooth /etc/rcP.d
[ -L "/etc/rc2.d/S25bluetooth" ] && /bin/rm /etc/rc2.d/S25bluetooth -f

echo postinst done
#DEBHELPER#
