Document: moko
Title: Debian moko Manual
Author: <insert document author here>
Abstract: This manual describes what moko is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/moko/moko.sgml.gz

Format: postscript
Files: /usr/share/doc/moko/moko.ps.gz

Format: text
Files: /usr/share/doc/moko/moko.text.gz

Format: HTML
Index: /usr/share/doc/moko/html/index.html
Files: /usr/share/doc/moko/html/*.html

  
