#!/usr/bin/python -u
# vim: ai ts=4 sts=4 et sw=4
#
# Copyright 2007, 2008 Intel Corporation
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),  
# to deal in the Software without restriction, including without limitation  
# the rights to use, copy, modify, merge, publish, distribute, sublicense,  
# and/or sell copies of the Software, and to permit persons to whom the  
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in 
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE 
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER 
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING 
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER 
# DEALINGS IN THE SOFTWARE.

import gettext
import gobject
import gtk
import gtk.gdk
import gtk.glade
import locale
import sys

sys.path.insert(0, '/usr/share/moblin-media')
from app import App

_ = gettext.lgettext

def main():
    gobject.threads_init()
    gtk.gdk.threads_init()

    # Setup basic internationalization, for more info see:
    # http://docs.python.org/lib/i18n.html
    locale.setlocale(locale.LC_ALL, '')
    for module in gtk.glade, gettext:
        module.bindtextdomain('moblin-media')
        module.textdomain('moblin-media')

    app = App()
    try:
        app.run()
    except:
        app.exit_interrupt()

if __name__ == '__main__':
    sys.exit(main())
